name: main
on:
  - pull_request
  - push
jobs:
  main:
    name: '${{ matrix.node }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
    strategy:
      matrix:
        node:
          - 10
          - node
